### ISSUE TITLE
Unexpected body hash mismatch error

### ISSUE THREAD

**Issue by s0undt3ch** [aenglander/practical-api-security-python-example-flask#1]
Followed your readme instructions.
I'm using Py 3.6.4 and created a virtualenv for your class where I installed your provided requirements file.
```
❯ export FLASK_APP=server.py
❯ export FLASK_ENV=development
❯ flask run
 * Serving Flask app "server"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```
```
❯ export FLASK_APP=server.py
❯ export FLASK_ENV=development
❯ python client.py
REQUEST:

=== No Request ===

RESPONSE:

Traceback (most recent call last):
  File "client.py", line 153, in <module>
    _verify_response(response)
  File "client.py", line 134, in _verify_response
    raise Exception("Unexpected response body_hash")
Exception: Unexpected response body_hash
```

Need any extra details?

**Comment by s0undt3ch** [comment]
```
❯ python client.py -v                                                                                                                                                                                    
REQUEST:

=== No Request ===
Request JWT Claims:
{
  "jti": "0946518e-538e-11e8-b317-448500121af1",
  "iat": 1525869414,
  "nbf": 1525869414,
  "exp": 1525869414,
  "iss": "valid-client",
  "aud": "api-server",
  "request": {                                                                                                                                                                                           
    "method": "GET",
    "path": "/"
  }
}

GET / HTTP/1.1
Authentication: EX-JWT eyJhbGciOiJIUzI1NiIsImtpZCI6ImtleTEifQ.eyJqdGkiOiAiMDk0NjUxOGUtNTM4ZS0xMWU4LWIzMTctNDQ4NTAwMTIxYWYxIiwgImlhdCI6IDE1MjU4Njk0MTQsICJuYmYiOiAxNTI1ODY5NDE0LCAiZXhwIjogMTUyNTg2OTQxNCwg
ImlzcyI6ICJ2YWxpZC1jbGllbnQiLCAiYXVkIjogImFwaS1zZXJ2ZXIiLCAicmVxdWVzdCI6IHsibWV0aG9kIjogIkdFVCIsICJwYXRoIjogIi8ifX0.Qx5fx0a2AF_UfxNNGm-Ul7CglMenVeowM6kGoQkoyTs

RESPONSE:

HTTP/1.1 200 OK
Content-Type: application/jose
X-JWT: eyJhbGciOiJIUzI1NiIsImtpZCI6ImtleTEifQ.eyJhdWQiOiAidmFsaWQtY2xpZW50IiwgImV4cCI6IDE1MjU4Njk0MTQsICJpYXQiOiAxNTI1ODY5NDE0LCAiaXNzIjogImFwaS1zZXJ2ZXIiLCAianRpIjogIjA5NDY1MThlLTUzOGUtMTFlOC1iMzE3LTQ0
ODUwMDEyMWFmMSIsICJuYmYiOiAxNTI1ODY5NDE0LCAicmVzcG9uc2UiOiB7ImJvZHlfaGFzaCI6ICIxMjNkNmYwNDJiMDA5YTZmYmMxZGQ0OWMwNDMxMTFiOTYzOGRlM2M4Y2M2MjY1ODgwMmM3MzA4MGUxZjQwY2QyZmRlN2IyOTJmYTRlZjA4ZTk3MjRmM2QxMTZlYm
Y3MTE1YzM4ZDZiMjY2YmZmOTE3OTg3NGQzNTFhY2U1YWEwMCIsICJib2R5X2hhc2hfYWxnIjogIlM1MTIiLCAic3RhdHVzX2NvZGUiOiAyMDB9fQ.dWDfDRGTBt-THpsYt-LaJBmKsJBbkrWdURILH4jZ2u0
Content-Length: 310
Server: Werkzeug/0.14.1 Python/3.6.4
Date: Wed, 09 May 2018 13:36:54 GMT

eyJhbGciOiJBMjU2S1ciLCJjdHkiOiJhcHBsaWNhdGlvbi9qc29uIiwiZW5jIjoiQTI1NkNCQy1IUzUxMiIsImtpZCI6ImtleTEifQ.vUjfJ5Ufb_N8hQobCklR7iG_jgEwZsU4a0CBAhNkzmpvWHNPLIL5fopocPC1yKGqmNQYleGY1KkqdR4pOtRkn_rZmv8ggcgG.fX
QM661qC7wzSPk5BcV13A.FbHAz3xZsEOF8vcCqjXJJjBrhF22C7Fjq1_PsfouW5A.bngv161chBMOKB1OPzzdLYBBxqoYlWZ-EtZ3Xu5BoHE

Response JWT Claims:
{
  "aud": "valid-client",
  "exp": 1525869414,
  "iat": 1525869414,
  "iss": "api-server",
  "jti": "0946518e-538e-11e8-b317-448500121af1",
  "nbf": 1525869414,
  "response": {
    "body_hash": "123d6f042b009a6fbc1dd49c043111b9638de3c8cc62658802c73080e1f40cd2fde7b292fa4ef08e9724f3d116ebf7115c38d6b266bff9179874d351ace5aa00",
    "body_hash_alg": "S512",
    "status_code": 200
  }
}

Traceback (most recent call last):
  File "client.py", line 153, in <module>
    _verify_response(response)
  File "client.py", line 134, in _verify_response
    raise Exception("Unexpected response body_hash")
Exception: Unexpected response body_hash
```

**Comment by s0undt3ch** [comment]
FYI, Just to test it out, I also had a Py3.5.4 pyenv for which I created a virtualenv and requirements, etc, and it worked.

**Comment by s0undt3ch** [comment]
So, went ahead and removed the Py 3.6.4 I had, rebuilt it, recreated the virtualenv, installed requirements, and funny enough, `pycryptodomex==3.5.1` was not in local pip cache when all other dependencies were.

Anyway, it works ™ !

**Comment by aenglander** [comment]
The hash issue occurs sporadically and makes no sense. It can often times be resolved by deactivating and reactivating the virtual env. The same issue also exists between Python 2 and 3.
